
package es.correos.oficinasbuzones;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Callejero", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://ide.cime.es/visoride/Callejero.asmx?wsdl")
public class Callejero
    extends Service
{

    private final static URL CALLEJERO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(es.correos.oficinasbuzones.Callejero.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = es.correos.oficinasbuzones.Callejero.class.getResource(".");
            url = new URL(baseUrl, "http://ide.cime.es/visoride/Callejero.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://ide.cime.es/visoride/Callejero.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CALLEJERO_WSDL_LOCATION = url;
    }

    public Callejero(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Callejero() {
        super(CALLEJERO_WSDL_LOCATION, new QName("http://tempuri.org/", "Callejero"));
    }

    /**
     * 
     * @return
     *     returns CallejeroSoap
     */
    @WebEndpoint(name = "CallejeroSoap")
    public CallejeroSoap getCallejeroSoap() {
        return super.getPort(new QName("http://tempuri.org/", "CallejeroSoap"), CallejeroSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CallejeroSoap
     */
    @WebEndpoint(name = "CallejeroSoap")
    public CallejeroSoap getCallejeroSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "CallejeroSoap"), CallejeroSoap.class, features);
    }

}
