
package es.correos.oficinasbuzones;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CallejeroSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CallejeroSoap {


    /**
     * 
     * @param idMunicipio
     * @return
     *     returns es.correos.oficinasbuzones.ArrayOfInt
     */
    @WebMethod(operationName = "EnvoltorioMunicipio", action = "http://tempuri.org/EnvoltorioMunicipio")
    @WebResult(name = "EnvoltorioMunicipioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EnvoltorioMunicipio", targetNamespace = "http://tempuri.org/", className = "es.correos.oficinasbuzones.EnvoltorioMunicipio")
    @ResponseWrapper(localName = "EnvoltorioMunicipioResponse", targetNamespace = "http://tempuri.org/", className = "es.correos.oficinasbuzones.EnvoltorioMunicipioResponse")
    public ArrayOfInt envoltorioMunicipio(
        @WebParam(name = "IdMunicipio", targetNamespace = "http://tempuri.org/")
        String idMunicipio);

    /**
     * 
     * @return
     *     returns es.correos.oficinasbuzones.ArrayOfMunicipio
     */
    @WebMethod(operationName = "Municipios", action = "http://tempuri.org/Municipios")
    @WebResult(name = "MunicipiosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Municipios", targetNamespace = "http://tempuri.org/", className = "es.correos.oficinasbuzones.Municipios")
    @ResponseWrapper(localName = "MunicipiosResponse", targetNamespace = "http://tempuri.org/", className = "es.correos.oficinasbuzones.MunicipiosResponse")
    public ArrayOfMunicipio municipios();

    /**
     * 
     * @param idMunicipio
     * @return
     *     returns es.correos.oficinasbuzones.ArrayOfNucleo
     */
    @WebMethod(operationName = "NucleosPorMunicipio", action = "http://tempuri.org/NucleosPorMunicipio")
    @WebResult(name = "NucleosPorMunicipioResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "NucleosPorMunicipio", targetNamespace = "http://tempuri.org/", className = "es.correos.oficinasbuzones.NucleosPorMunicipio")
    @ResponseWrapper(localName = "NucleosPorMunicipioResponse", targetNamespace = "http://tempuri.org/", className = "es.correos.oficinasbuzones.NucleosPorMunicipioResponse")
    public ArrayOfNucleo nucleosPorMunicipio(
        @WebParam(name = "IdMunicipio", targetNamespace = "http://tempuri.org/")
        String idMunicipio);

    /**
     * 
     * @param idNucleo
     * @return
     *     returns es.correos.oficinasbuzones.ArrayOfCalle
     */
    @WebMethod(operationName = "CallesPorNucleo", action = "http://tempuri.org/CallesPorNucleo")
    @WebResult(name = "CallesPorNucleoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CallesPorNucleo", targetNamespace = "http://tempuri.org/", className = "es.correos.oficinasbuzones.CallesPorNucleo")
    @ResponseWrapper(localName = "CallesPorNucleoResponse", targetNamespace = "http://tempuri.org/", className = "es.correos.oficinasbuzones.CallesPorNucleoResponse")
    public ArrayOfCalle callesPorNucleo(
        @WebParam(name = "IdNucleo", targetNamespace = "http://tempuri.org/")
        String idNucleo);

    /**
     * 
     * @param idCalle
     * @return
     *     returns es.correos.oficinasbuzones.ArrayOfPortal
     */
    @WebMethod(operationName = "PortalesPorCalle", action = "http://tempuri.org/PortalesPorCalle")
    @WebResult(name = "PortalesPorCalleResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PortalesPorCalle", targetNamespace = "http://tempuri.org/", className = "es.correos.oficinasbuzones.PortalesPorCalle")
    @ResponseWrapper(localName = "PortalesPorCalleResponse", targetNamespace = "http://tempuri.org/", className = "es.correos.oficinasbuzones.PortalesPorCalleResponse")
    public ArrayOfPortal portalesPorCalle(
        @WebParam(name = "IdCalle", targetNamespace = "http://tempuri.org/")
        String idCalle);

}
