
package com.ipartek.formacion;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "peliculasservice", targetNamespace = "http://ws.formacion.ipartek.com/", wsdlLocation = "http://localhost:8080/webservices-jaxws/peliculasws?wsdl")
public class Peliculasservice
    extends Service
{

    private final static URL PELICULASSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.ipartek.formacion.Peliculasservice.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.ipartek.formacion.Peliculasservice.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/webservices-jaxws/peliculasws?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/webservices-jaxws/peliculasws?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PELICULASSERVICE_WSDL_LOCATION = url;
    }

    public Peliculasservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Peliculasservice() {
        super(PELICULASSERVICE_WSDL_LOCATION, new QName("http://ws.formacion.ipartek.com/", "peliculasservice"));
    }

    /**
     * 
     * @return
     *     returns PeliculasServiceWSImp
     */
    @WebEndpoint(name = "PeliculasServiceWSImpPort")
    public PeliculasServiceWSImp getPeliculasServiceWSImpPort() {
        return super.getPort(new QName("http://ws.formacion.ipartek.com/", "PeliculasServiceWSImpPort"), PeliculasServiceWSImp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PeliculasServiceWSImp
     */
    @WebEndpoint(name = "PeliculasServiceWSImpPort")
    public PeliculasServiceWSImp getPeliculasServiceWSImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.formacion.ipartek.com/", "PeliculasServiceWSImpPort"), PeliculasServiceWSImp.class, features);
    }

}
