
package com.ipartek.formacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PeliculasServiceWSImp", targetNamespace = "http://ws.formacion.ipartek.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PeliculasServiceWSImp {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.ipartek.formacion.PeliculaMensaje
     */
    @WebMethod(operationName = "obtenerporid_peli")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerporid_peli", targetNamespace = "http://ws.formacion.ipartek.com/", className = "com.ipartek.formacion.ObtenerporidPeli")
    @ResponseWrapper(localName = "obtenerporid_peliResponse", targetNamespace = "http://ws.formacion.ipartek.com/", className = "com.ipartek.formacion.ObtenerporidPeliResponse")
    public PeliculaMensaje obtenerporidPeli(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns com.ipartek.formacion.PeliculaColeccion
     */
    @WebMethod(operationName = "obtenerTodos_peli")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerTodos_peli", targetNamespace = "http://ws.formacion.ipartek.com/", className = "com.ipartek.formacion.ObtenerTodosPeli")
    @ResponseWrapper(localName = "obtenerTodos_peliResponse", targetNamespace = "http://ws.formacion.ipartek.com/", className = "com.ipartek.formacion.ObtenerTodosPeliResponse")
    public PeliculaColeccion obtenerTodosPeli();

}
